version: '2'
services:
  database:
    image: mysql:latest
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database:/var/lib/mysql
      - ./config/db:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3366:3306
    expose:
      - 3366
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=abcd1234
      - MYSQL_DATABASE=ttapp

  php-fpm:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www:cached
    ports:
        - "9000:9000"

  webserver:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./api:/var/www:cached
      - ./config/web/site.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/var/www/html
    links:
      - php-fpm
    depends_on:
      - database


