version: '2'
services:
  database:
    image: mysql:latest
    command: mysqld --sql_mode="" 
    volumes:
      - ./database:/var/lib/mysql
      - ./config/db:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=abcd1234
      - MYSQL_DATABASE=ttapp

  php-fpm:
    build:
      context: .
      dockerfile: ./config/php/Dockerfile
    volumes:
      - ./api:/var/www
    ports:
        - "9000:9000"

  webserver:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./api:/var/www
      - ./config/web/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    depends_on:
      - database

  app:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229" 
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules
    depends_on:
      - database
    command: npm run start 