version: '2'
services:
  web:
    build: 
      dockerfile: Dockerfile-app
      context: .
    command: npm start
    volumes:
      - "./src:/usr/app/src"
    ports:
      - "3000:3000"
  api:
    build:
      dockerfile: Dockerfile-go
      context: .

