player:
  path: /players/{id}
  controller: App\Controller\PlayerController::getPlayerById
  methods: [GET]
  requirements:
    id: '\d+'

players:
  path: /players
  controller: App\Controller\PlayerController::getPlayers
  methods: [GET]

player_add:
  path: /players/add
  controller: App\Controller\PlayerController::addPlayer
  methods: [POST]

match_mode:
  path: /matches/modes/{id}
  controller: App\Controller\MatchModeController::getMatchModeById

match_modes:
  path: /matches/modes
  controller: App\Controller\MatchModeController::getMatchModes
