match_mode:
  path: /matches/modes/{id}
  controller: App\Controller\MatchModeController::getMatchModeById

match_modes:
  path: /matches/modes
  controller: App\Controller\MatchModeController::getMatchModes

matches:
  path: /matches
  controller: App\Controller\MatchController:getMatches

player:
  path: /players/{id}
  controller: App\Controller\PlayerController::getPlayerById
  methods: [GET]
  requirements:
    id: '\d+'

players:
  path: /players
  controller: App\Controller\PlayerController::getPlayers
  methods: [GET]

player_add:
  path: /players/add
  controller: App\Controller\PlayerController::addPlayer
  methods: [POST]

tournament:
  path: /tournaments/{id}
  controller: App\Controller\TournamentController::getTournamentById
  methods: [GET]
  requirements:
    id: '\d+'

tournaments:
  path: /tournaments
  controller: App\Controller\TournamentController::getTournaments
  methods: [GET]

tournament_add:
  path: /tournaments/add
  controller: App\Controller\TournamentController::addTournament
  methods: [POST]

group_add:
  path: /groups/add
  controller: App\Controller\TournamentGroupController::addTournamentGroup
  methods: [POST]

groups_by_tournament:
  path: /groups/tournaments/{id}
  controller: App\Controller\TournamentGroupController::getTournamentGroupsByTournamentId
  methods: [GET]
  requirements:
    id: '\d+'