# PLAYER ROUTES

players:
  path: /players
  controller: App\Controller\PlayerController::getPlayers
  methods: [GET]

player:
  path: /players/{id}
  controller: App\Controller\PlayerController::getPlayerById
  methods: [GET]
  requirements:
    id: '\d+'

player_results:
  path: /players/{id}/results
  controller: App\Controller\PlayerController::getPlayerResults
  methods: [GET]
  requirements:
    id: '\d+'

player_add:
  path: /players/add
  controller: App\Controller\PlayerController::addPlayer
  methods: [POST]

# TOURNAMENT ROUTES

tournaments:
  path: /tournaments
  controller: App\Controller\TournamentController::getTournaments
  methods: [GET]

tournament_add:
  path: /tournaments/add
  controller: App\Controller\TournamentController::addTournament
  methods: [POST]

tournament:
  path: /tournaments/{id}
  controller: App\Controller\TournamentController::getTournamentById
  methods: [GET]
  requirements:
    id: '\d+'

tournament_standings:
  path: /tournaments/{id}/standings
  controller: App\Controller\TournamentController::getStandings
  requirements:
    id: '\d+'

tournament_results:
  path: /tournaments/{tournamentId}/results/{numberOfResults}
  controller: App\Controller\TournamentController:getTournamentResults
  requirements:
    tournamentId: '\d+'
    numberOfResults: '\d+'

tournament_schedule:
  path: /tournaments/{tournamentId}/fixtures/{numberOfFixtures}
  controller: App\Controller\TournamentController:getTournamentSchedule
  requirements:
    tournamentId: '\d+'
    numberOfFixtures: '\d+'

# GROUP ROUTES

groups_by_tournament:
  path: /groups/tournaments/{id}
  controller: App\Controller\TournamentGroupController::getTournamentGroupsByTournamentId
  methods: [GET]
  requirements:
    id: '\d+'

group_add:
  path: /groups/add
  controller: App\Controller\TournamentGroupController::addTournamentGroup
  methods: [POST]

# MATCH MODE ROUTES

match_mode:
  path: /matches/modes/{id}
  controller: App\Controller\MatchModeController::getMatchModeById

match_modes:
  path: /matches/modes
  controller: App\Controller\MatchModeController::getMatchModes

# MATCH ROUTES

match_add:
  path: /matches/add/official
  controller: App\Controller\MatchController::addMatch
  methods: [POST]

match_save:
  path: /matches/save
  controller: App\Controller\MatchController::saveMatch
  methods: [POST]

matches_all:
  path: /matches
  controller: App\Controller\MatchController:getAllMatches

